"""initial schema

Revision ID: 4d68293afe45
Revises: 
Create Date: 2026-07-24 00:52:39.343123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d68293afe45'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screening_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('rule_version', sa.String(length=20), nullable=False),
    sa.Column('feature_weights_snapshot', sa.JSON(), nullable=False),
    sa.Column('watchlist_score', sa.Integer(), nullable=False),
    sa.Column('watchlist_status', sa.String(length=50), nullable=True),
    sa.Column('param_results', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screening_snapshots_customer_id'), 'screening_snapshots', ['customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_screening_snapshots_customer_id'), table_name='screening_snapshots')
    op.drop_table('screening_snapshots')
    # ### end Alembic commands ###
